### ISSUE TITLE
Certain non-panorama photos are flagged as panoramas

### ISSUE THREAD

**Issue by mipoon** [frapa/sampan#2]
Hi, I have seen some instances where a non-panorama photo is being flagged as a panorama.  Attached are two examples.  For 20220115_071307.jpg (the beach photo), sampan appears to modify the photo, believing it to be a panorama.  For 20220530_092325.jpg (the dragonfly), a message states that the photo is an unknown panorama version:

$ sampan pans/*.jpg -i
pans/20220115_071307.jpg -> pans/20220115_071307.jpg
  Extracting 3.3 of 3.3 MB (100 %)
pans/20220530_092325.jpg: Unknown panorama version 107, sampan only supports version 101, 103, 105, 106 [skip]

---
Extracted 5 of 5 MB (100 %) -- Time: 0.007 s
![20220115_071307](https://user-images.githubusercontent.com/107957557/175110888-4f0ac038-3cd3-49e0-b3e1-f8b2e465be09.jpg)
![20220530_092325](https://user-images.githubusercontent.com/107957557/175110890-dc2d4bf7-efc8-4dab-887e-20cec43f4995.jpg)

**Comment by frapa** [comment]
@mipoon The first is expected behavior. Photos taken with Samsung devices, including wide selfies, photos takes with the motion video feature activated or sometimes even plain pictures contain an extra, Samsung-specific "footer". The data that usually comes in this footer is usually a video file, but it can also be just a small footer with some Samsung-specific information. `sampan` basically removes data after this footer, making the files normal JPEG files again. Note that the footer can cause certain programs to be unable to open the files, even if they are just some Samsung-specific metadata.

In your first example, the photo contains one of these small footers, which `sampan` removes. The size of the photo does not change because the footer is small. If you look at the size in bytes, you will se that it removed some bytes.

Therefore it's not "believing that it's a panorama". `sampan`, despite the name, can fix other image types as well.

In the second picture, there is an footer format that is not supported by `sampan` (most likely because I did not have a picture to test it), so it fails instead of possibly corrupting your image. I can now have a look thanks to your image. 

BTW, you can use the `-f` option to force converting your file even if the version does not match.

Will be back soon.

**Comment by frapa** [comment]
I released a patch version which should solve the second error. Could you try @mipoon?

**Comment by mipoon** [comment]
@frapa - The patched version seems to work well!  I have tried it on several hundred of my JPG photos, all taken with a Galaxy S20 FE.  In the original version, I saw a lot of warnings about the unknown version.  With the patched version, I only messages indicating a successful extraction or "Image is not a Samsung panorama."

Thank you so much for your patience in explaining everything and producing a patch so quickly.  I was very frustrated with Lightroom not reading my panoramas and never considered it was Samsung creating their JPGs in a non-standard way.  This tool has really saved the day!

**Comment by frapa** [comment]
I am happy it worked for you, I wrote it for the same reason!

Probably, Samsung is adding new types or formats of footers every some new version of their phones.

One last question: how was the performance of the tool for you? Was the extraction of hundred of files fast? Could you tell me like ballpark numbers of images and time?

**Comment by mipoon** [comment]
The performance seemed great.  I ran it on 879 files and it only took about 4 seconds.  The final message was:

Extracted 2403 of 2403 MB (100 %) -- Time: 3.977 s
